### ISSUE TITLE
Chapter7/serverAppSpec.js: e.cookies is not function

### ISSUE THREAD

**Issue by jdunham2** [shyamseshadri/angularjs-up-and-running#19]
Chrome 43.0.2357 (Mac OS X 10.10.3) MainCtrl Server Calls should load items from server FAILED
TypeError: e.cookies is not a function
 at n (Sites/sandbox/gitHub_basics/angular/angular.min.js:82:350) ...

Not sure why this error is happening, copied and pasted the example from gitHub and still get it :/

**Comment by shyamseshadri** [comment]
Just did a clean checkout and tried running the tests, couldn't reproduce this. 

Could you try cloning this repo and trying to run the tests?

**Comment by jdunham2** [comment]
Hey Shyam,

Odd, when I cloned it like you said, it worked!  Not sure whats wrong with my repository ...

Thanks! Loving the book.

**Comment by jdunham2** [comment]
I reinitialized Karma with fresh angular.min.js and angular-mocks.js and this cleared up the error.

**Comment by shyamseshadri** [comment]
Hrm, it could be because the versions of AngularJS in min.js and mocks.js
might have been different. You could check that I guess.
